"use strict";
let message = "hello adil";
console.log(message);
console.log(message);
console.log(message);
console.log(message);
console.log(message);
console.log(message);
let numberone = 3;
let numbertwo = 4;
let sum = numberone + numbertwo;
console.log(sum);
let greetings = "hello adil";
console.log(greetings);
let calculateone = 2;
let calculatetwo = 5;
let add = calculateone + calculatetwo;
console.log(add);
